Metrics/LineLength:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false
Lint/UnneededCopDisableDirective:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
